# Generated by Django 5.2.7 on 2026-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyexpense',
            old_name='food_cost',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='weeklyexpense',
            old_name='driver_name',
            new_name='person_name',
        ),
        migrations.RemoveField(
            model_name='weeklyexpense',
            name='petrol_cost',
        ),
        migrations.AddField(
            model_name='weeklyexpense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyexpense',
            name='title',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
