# Generated by Django 5.2.7 on 2026-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.IntegerField(default=1)),
                ('selected', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
