# Generated by Django 5.2.7 on 2026-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.IntegerField(choices=[(1, 'First Round'), (2, 'Second Technical'), (3, 'Client Technical'), (4, 'Technical HR'), (5, 'Final Decision')], default=1),
        ),
    ]
